services:
  postgres:
    image: 'postgres:15.4-alpine'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=orderhere'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
  minio:
    image: minio/minio
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

volumes:
  minio_data: {}

#  rabbitmq:
#    image: 'rabbitmq:latest'
#    environment:
#      - 'RABBITMQ_DEFAULT_PASS=orderhere'
#      - 'RABBITMQ_DEFAULT_USER=rabbitmq'
#    ports:
#      - '5672:5672'
