version: '3.8'

services:
  postgres:
    image: 'postgres:15.4-alpine'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=orderhere'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    networks:
      - app-network

  minio:
    image: minio/minio
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    networks:
      - app-network

  app:
    build:
      context: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: orderhere
      STORAGE_URL: http://minio:9000
      STRIPE_API_KEY: ${STRIPE_API_KEY}
    depends_on:
      - postgres
      - minio
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  minio_data: {}

networks:
  app-network: