spring:
  config:
    activate:
      on-profile: development
    import:
      - aws-parameterstore:/config/orderhere-monolithic/development/spring/datasource?prefix=spring.datasource.
      - aws-parameterstore:/config/orderhere-monolithic/development/spring/storage?prefix=storage
      - aws-secretsmanager:rds!db-fd18de7b-4dbe-4e38-b479-7176428845ed?prefix=spring.datasource.
  cloud:
    aws:
      region:
        static: ap-southeast-2
      credentials:
        profile:
          name: default
  datasource:
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: false
    clean-on-validation-error: true
    locations: classpath:db/migration
    schemas: public
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}