spring:
  config:
    activate:
      on-profile: development
    import: aws-parameterstore:/config/orderhere-monolithic/development/spring/datasource?prefix=spring.datasource.
  cloud:
    aws:
      region:
        static: ap-southeast-2
      credentials:
        profile:
          name: default
  datasource:
    # url: jdbc:postgresql://localhost:5432/postgres
    # username: postgres
    # password: orderhere
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: false
    clean-on-validation-error: true
    locations: classpath:db/migration
    schemas: public
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}