spring:
  config:
    activate:
      on-profile: local
  cloud:
    aws:
      region:
        static: ap-southeast-2
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: orderhere
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: false
    clean-on-validation-error: true
    locations: classpath:db/migration
    schemas: public
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7080/realms/orderhere

keyCloak:
  serverUrl: http://localhost:7080
  realm: orderhere
  clientId: admin-cli
  username: admin-keycloak
  password: admin-keycloak
  jwt:
    publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0qpWkdz7kIomLQcd6HLvz0mPbQptypl3JPQyrpE9lzs6fqJpqomlpQxPoxnFAentrnGoXzAk05ufsaX2p79Bj6Z/mY3QCXiM83h3k5JPQsChS5lDYpsEnmC9JGIG8BUrx7yaRRKG7TW30DSo2EHIdaUKNggimODfnLRTLd+yQST7V//2ZzO5/4fi/Q5UZW9s/V1tTEsuBJe1tGb+FUiOvXHUGBmT+OeJPfJkyfQEeMLQ41zCpZdYLa5NI1S7t/l81fU45/ZdDlE46PmDwfySAb7wTT5R7cdSCt/WWwcOTj4JxBcGc3+2vmyLtJCbcTXQ5MXWdN1T4MGvXnUKkHdzIwIDAQAB

storage:
  bucketName: my-bucket
  url: http://127.0.0.1:9000