server:
  port: 8080

spring:
  profiles:
    active: local
  application:
    name: orderhere
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 4MB
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  graphql:
    path: /graphql
    graphiql:
      enabled: true
      path: /graphiql
resilience4j:
  retry:
    instances:
      default:
        maxAttempts: 2
        waitDuration: 500ms
  circuitbreaker:
    instances:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
  ratelimiter:
    instances:
      default:
        limitForPeriod: 50
        timeoutDuration: 5s
        limit-refresh-period:
          nanos: 10000
  bulkhead:
    instances:
      default:
        maxConcurrentCalls: 100
        maxWaitDuration: 300ms
