spring:
  config:
    activate:
      on-profile: development
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5432/postgres}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:orderhere}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: false
    clean-on-validation-error: true
    locations: classpath:db/migration
    schemas: public
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}