spring:
  config:
    activate:
      on-profile: local
  cloud:
    aws:
      region:
        static: ap-southeast-2
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: orderhere
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: false
    clean-on-validation-error: true
    locations: classpath:db/migration
    schemas: public
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7080/realms/orderhere

storage:
  bucketName: my-bucket
  url: http://127.0.0.1:9000