server:
  port: 8080

spring:
  profiles:
    active: development
  application:
    name: orderhere
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 4MB
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate